model:
    name: pose_net
    feature_extractor:
        name: resnet34
        pretrained: True
    criterion:
        name: se3
    feature_dimension: 2048
    drop_rate: 0.5
    optimizer:
        betas: 0.9 0.999
        lr: 0.0001

max_epochs: 10
