model:
    name: pose_net
    feature_extractor:
        name: resnet34
        pretrained: True
    criterion:
        name: se3
#        rotation_koef: -3.0
    feature_dimension: 2048
    drop_rate: 0.1
    optimizer:
        betas: 0.9 0.999
        lr: 0.0001
        weight_decay: 0.0005
    bias: True

max_epochs: 10
