model:
    name: pose_net
    feature_extractor:
        name: ipl_cnn
        pretrained: True
    criterion:
        name: se3
        rotation_koef: -3.0
        translation_koef: -3.0
    feature_dimension: 2048
    drop_rate: 0.15
    optimizer:
        betas: 0.9 0.999
        lr: 0.01
        weight_decay: 0.0005
    scheduler:
        step_size: 20
        gamma: 0.5
    bias: True
    activation: relu

data_module:
    batch_size: 32
    use_test: True
    num_workers: 4
    image_size: 256

max_epochs: 300
