model:
    name: pose_net
    feature_extractor:
        name: resnet34
        pretrained: True
    criterion:
        name: pose_net_criterion
    feature_dimension: 2048
    drop_rate: 0.4
    optimizer:
        betas: 0.9 0.999
